-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
--
-- Add any additional autocmds here
-- with `vim.api.nvim_create_autocmd`
--
-- Or remove existing autocmds by their group name (which is prefixed with `lazyvim_` for the defaults)
-- e.g. vim.api.nvim_del_augroup_by_name("lazyvim_wrap_spell")

-- vim.filetype.add({
--   extension = {
--     sv = "systemverilog",
--     svh = "systemverilog",
--     v = "verilog",
--     vh = "verilog",
--   },
-- })
--


-- CURRENT HOURS WASTED TRYING TO FIX SYSTEMVERILOG SLOWDOWN [[5]]
-- Disable treesitter on BufReadPre, enable after BufReadPost
-- vim.api.nvim_create_autocmd("BufReadPre", {
--   pattern = "*.sv,*.svh,*.v,*.vh",
--   callback = function()
--     vim.cmd("TSBufDisable highlight")
--     vim.cmd("TSBufDisable BufReadPost")
--     vim.cmd("TSBufDisable textobjects")
--   end,
-- })
--
-- vim.api.nvim_create_autocmd("BufReadPost", {
--   pattern = "*.sv,*.svh,*.v,*.vh",
--   callback = function()
--     vim.defer_fn(function()
--       vim.cmd("TSBufEnable highlight")
--       vim.cmd("TSBufEnable BufReadPost")
--       vim.cmd("TSBufEnable textobjects")
--     end, 200)
--   end,
-- })
--

